name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v2
    with:
      rust-toolchain: nightly-2023-02-15
      vmtools-version: v1.5.3
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
